---
# tasks file for roles/rabbitmq

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install required packages
  apt:
    name:
      - curl
      - gnupg
    state: present

- name: Ensure apt-transport-https is installed
  apt:
    name: apt-transport-https
    state: present
    update_cache: yes

- name: Add RabbitMQ Team GPG key
  shell: |
    curl -1sLf "https://keys.openpgp.org/vks/v1/by-fingerprint/0A9AF2115F4687BD29803A206B73A36E6026DFCA" | \
    gpg --dearmor | \
    tee /usr/share/keyrings/com.rabbitmq.team.gpg
  args:
    executable: /bin/bash

- name: Add Cloudsmith Erlang GPG key
  shell: |
    curl -1sLf https://github.com/rabbitmq/signing-keys/releases/download/3.0/cloudsmith.rabbitmq-erlang.E495BB49CC4BBE5B.key | \
    gpg --dearmor | \
    tee /usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.gpg
  args:
    executable: /bin/bash

- name: Add Cloudsmith RabbitMQ GPG key
  shell: |
    curl -1sLf https://github.com/rabbitmq/signing-keys/releases/download/3.0/cloudsmith.rabbitmq-server.9F4587F226208342.key | \
    gpg --dearmor | \
    tee /usr/share/keyrings/rabbitmq.9F4587F226208342.gpg
  args:
    executable: /bin/bash

- name: Add RabbitMQ APT repository list
  copy:
    dest: /etc/apt/sources.list.d/rabbitmq.list
    content: |
      deb [arch=amd64 signed-by=/usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.gpg] https://ppa1.rabbitmq.com/rabbitmq/rabbitmq-erlang/deb/ubuntu jammy main
      deb-src [signed-by=/usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.gpg] https://ppa1.rabbitmq.com/rabbitmq/rabbitmq-erlang/deb/ubuntu jammy main
      deb [arch=amd64 signed-by=/usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.gpg] https://ppa2.rabbitmq.com/rabbitmq/rabbitmq-erlang/deb/ubuntu jammy main
      deb-src [signed-by=/usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.gpg] https://ppa2.rabbitmq.com/rabbitmq/rabbitmq-erlang/deb/ubuntu jammy main
      deb [arch=amd64 signed-by=/usr/share/keyrings/rabbitmq.9F4587F226208342.gpg] https://ppa1.rabbitmq.com/rabbitmq/rabbitmq-server/deb/ubuntu jammy main
      deb-src [signed-by=/usr/share/keyrings/rabbitmq.9F4587F226208342.gpg] https://ppa1.rabbitmq.com/rabbitmq/rabbitmq-server/deb/ubuntu jammy main
      deb [arch=amd64 signed-by=/usr/share/keyrings/rabbitmq.9F4587F226208342.gpg] https://ppa2.rabbitmq.com/rabbitmq/rabbitmq-server/deb/ubuntu jammy main
      deb-src [signed-by=/usr/share/keyrings/rabbitmq.9F4587F226208342.gpg] https://ppa2.rabbitmq.com/rabbitmq/rabbitmq-server/deb/ubuntu jammy main
    owner: root
    group: root
    mode: '0644'

- name: Update apt cache after adding repositories
  apt:
    update_cache: yes

- name: Install Erlang dependencies
  apt:
    name:
      - erlang-base
      - erlang-asn1
      - erlang-crypto
      - erlang-eldap
      - erlang-ftp
      - erlang-inets
      - erlang-mnesia
      - erlang-os-mon
      - erlang-parsetools
      - erlang-public-key
      - erlang-runtime-tools
      - erlang-snmp
      - erlang-ssl
      - erlang-syntax-tools
      - erlang-tftp
      - erlang-tools
      - erlang-xmerl
    state: present

- name: Install RabbitMQ server
  apt:
    name: rabbitmq-server
    state: present
    update_cache: yes


- name: Start RabbitMQ service
  systemd:
    name: rabbitmq-server
    state: started
    enabled: yes

- name: Enable RabbitMQ management plugin
  command: rabbitmq-plugins enable rabbitmq_management

- name: Restart RabbitMQ service
  systemd:
    name: rabbitmq-server
    state: restarted

# Then run 

#    sudo rabbitmqctl add_user 'admin' 'password'
#    sudo rabbitmqctl set_user_tags admin administrator
#    sudo rabbitmqctl set_permissions -p / admin ".*" ".*" ".*"
