---
- name: Test apt update on prod server
  hosts: prod
  become: true

  tasks:
    - name: Run apt update
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade all packages
      apt:
        upgrade: dist